#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BIBLIOTECA")]
	public partial class DbLibraryEntityDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTD_Reserva_Espacio_Trabajo(TD_Reserva_Espacio_Trabajo instance);
    partial void UpdateTD_Reserva_Espacio_Trabajo(TD_Reserva_Espacio_Trabajo instance);
    partial void DeleteTD_Reserva_Espacio_Trabajo(TD_Reserva_Espacio_Trabajo instance);
    partial void InsertTM_Salones_Reunione(TM_Salones_Reunione instance);
    partial void UpdateTM_Salones_Reunione(TM_Salones_Reunione instance);
    partial void DeleteTM_Salones_Reunione(TM_Salones_Reunione instance);
    partial void InsertTD_Reserva_Libro(TD_Reserva_Libro instance);
    partial void UpdateTD_Reserva_Libro(TD_Reserva_Libro instance);
    partial void DeleteTD_Reserva_Libro(TD_Reserva_Libro instance);
    partial void InsertTD_Reserva_salones_reunione(TD_Reserva_salones_reunione instance);
    partial void UpdateTD_Reserva_salones_reunione(TD_Reserva_salones_reunione instance);
    partial void DeleteTD_Reserva_salones_reunione(TD_Reserva_salones_reunione instance);
    partial void InsertTM_Espacio_Trabajo(TM_Espacio_Trabajo instance);
    partial void UpdateTM_Espacio_Trabajo(TM_Espacio_Trabajo instance);
    partial void DeleteTM_Espacio_Trabajo(TM_Espacio_Trabajo instance);
    partial void InsertTM_Estudiante(TM_Estudiante instance);
    partial void UpdateTM_Estudiante(TM_Estudiante instance);
    partial void DeleteTM_Estudiante(TM_Estudiante instance);
    partial void InsertTM_Libro(TM_Libro instance);
    partial void UpdateTM_Libro(TM_Libro instance);
    partial void DeleteTM_Libro(TM_Libro instance);
    #endregion
		
		public DbLibraryEntityDataContext() : 
				base(global::CapaDatos.Properties.Settings.Default.BIBLIOTECAConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbLibraryEntityDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbLibraryEntityDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbLibraryEntityDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbLibraryEntityDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TD_Reserva_Espacio_Trabajo> TD_Reserva_Espacio_Trabajos
		{
			get
			{
				return this.GetTable<TD_Reserva_Espacio_Trabajo>();
			}
		}
		
		public System.Data.Linq.Table<TM_Salones_Reunione> TM_Salones_Reuniones
		{
			get
			{
				return this.GetTable<TM_Salones_Reunione>();
			}
		}
		
		public System.Data.Linq.Table<TD_Reserva_Libro> TD_Reserva_Libros
		{
			get
			{
				return this.GetTable<TD_Reserva_Libro>();
			}
		}
		
		public System.Data.Linq.Table<TD_Reserva_salones_reunione> TD_Reserva_salones_reuniones
		{
			get
			{
				return this.GetTable<TD_Reserva_salones_reunione>();
			}
		}
		
		public System.Data.Linq.Table<TM_Espacio_Trabajo> TM_Espacio_Trabajos
		{
			get
			{
				return this.GetTable<TM_Espacio_Trabajo>();
			}
		}
		
		public System.Data.Linq.Table<TM_Estudiante> TM_Estudiantes
		{
			get
			{
				return this.GetTable<TM_Estudiante>();
			}
		}
		
		public System.Data.Linq.Table<TM_Libro> TM_Libros
		{
			get
			{
				return this.GetTable<TM_Libro>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TD_Reserva_Espacio_Trabajo")]
	public partial class TD_Reserva_Espacio_Trabajo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Reserva_Espacio;
		
		private int _Matricula;
		
		private int _ID_Espacio;
		
		private System.DateTime _Inicio_Reserva;
		
		private System.DateTime _Final_Reserva;
		
		private EntityRef<TM_Espacio_Trabajo> _TM_Espacio_Trabajo;
		
		private EntityRef<TM_Estudiante> _TM_Estudiante;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_Reserva_EspacioChanging(int value);
    partial void OnID_Reserva_EspacioChanged();
    partial void OnMatriculaChanging(int value);
    partial void OnMatriculaChanged();
    partial void OnID_EspacioChanging(int value);
    partial void OnID_EspacioChanged();
    partial void OnInicio_ReservaChanging(System.DateTime value);
    partial void OnInicio_ReservaChanged();
    partial void OnFinal_ReservaChanging(System.DateTime value);
    partial void OnFinal_ReservaChanged();
    #endregion
		
		public TD_Reserva_Espacio_Trabajo()
		{
			this._TM_Espacio_Trabajo = default(EntityRef<TM_Espacio_Trabajo>);
			this._TM_Estudiante = default(EntityRef<TM_Estudiante>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Reserva_Espacio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Reserva_Espacio
		{
			get
			{
				return this._ID_Reserva_Espacio;
			}
			set
			{
				if ((this._ID_Reserva_Espacio != value))
				{
					this.OnID_Reserva_EspacioChanging(value);
					this.SendPropertyChanging();
					this._ID_Reserva_Espacio = value;
					this.SendPropertyChanged("ID_Reserva_Espacio");
					this.OnID_Reserva_EspacioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matricula", DbType="Int NOT NULL")]
		public int Matricula
		{
			get
			{
				return this._Matricula;
			}
			set
			{
				if ((this._Matricula != value))
				{
					if (this._TM_Estudiante.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMatriculaChanging(value);
					this.SendPropertyChanging();
					this._Matricula = value;
					this.SendPropertyChanged("Matricula");
					this.OnMatriculaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Espacio", DbType="Int NOT NULL")]
		public int ID_Espacio
		{
			get
			{
				return this._ID_Espacio;
			}
			set
			{
				if ((this._ID_Espacio != value))
				{
					if (this._TM_Espacio_Trabajo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_EspacioChanging(value);
					this.SendPropertyChanging();
					this._ID_Espacio = value;
					this.SendPropertyChanged("ID_Espacio");
					this.OnID_EspacioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inicio_Reserva", DbType="DateTime NOT NULL")]
		public System.DateTime Inicio_Reserva
		{
			get
			{
				return this._Inicio_Reserva;
			}
			set
			{
				if ((this._Inicio_Reserva != value))
				{
					this.OnInicio_ReservaChanging(value);
					this.SendPropertyChanging();
					this._Inicio_Reserva = value;
					this.SendPropertyChanged("Inicio_Reserva");
					this.OnInicio_ReservaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Final_Reserva", DbType="DateTime NOT NULL")]
		public System.DateTime Final_Reserva
		{
			get
			{
				return this._Final_Reserva;
			}
			set
			{
				if ((this._Final_Reserva != value))
				{
					this.OnFinal_ReservaChanging(value);
					this.SendPropertyChanging();
					this._Final_Reserva = value;
					this.SendPropertyChanged("Final_Reserva");
					this.OnFinal_ReservaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Espacio_Trabajo_TD_Reserva_Espacio_Trabajo", Storage="_TM_Espacio_Trabajo", ThisKey="ID_Espacio", OtherKey="ID_Espacio", IsForeignKey=true)]
		public TM_Espacio_Trabajo TM_Espacio_Trabajo
		{
			get
			{
				return this._TM_Espacio_Trabajo.Entity;
			}
			set
			{
				TM_Espacio_Trabajo previousValue = this._TM_Espacio_Trabajo.Entity;
				if (((previousValue != value) 
							|| (this._TM_Espacio_Trabajo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TM_Espacio_Trabajo.Entity = null;
						previousValue.TD_Reserva_Espacio_Trabajos.Remove(this);
					}
					this._TM_Espacio_Trabajo.Entity = value;
					if ((value != null))
					{
						value.TD_Reserva_Espacio_Trabajos.Add(this);
						this._ID_Espacio = value.ID_Espacio;
					}
					else
					{
						this._ID_Espacio = default(int);
					}
					this.SendPropertyChanged("TM_Espacio_Trabajo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Estudiante_TD_Reserva_Espacio_Trabajo", Storage="_TM_Estudiante", ThisKey="Matricula", OtherKey="Matricula", IsForeignKey=true)]
		public TM_Estudiante TM_Estudiante
		{
			get
			{
				return this._TM_Estudiante.Entity;
			}
			set
			{
				TM_Estudiante previousValue = this._TM_Estudiante.Entity;
				if (((previousValue != value) 
							|| (this._TM_Estudiante.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TM_Estudiante.Entity = null;
						previousValue.TD_Reserva_Espacio_Trabajos.Remove(this);
					}
					this._TM_Estudiante.Entity = value;
					if ((value != null))
					{
						value.TD_Reserva_Espacio_Trabajos.Add(this);
						this._Matricula = value.Matricula;
					}
					else
					{
						this._Matricula = default(int);
					}
					this.SendPropertyChanged("TM_Estudiante");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TM_Salones_Reuniones")]
	public partial class TM_Salones_Reunione : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Salon;
		
		private string _Nombre_Salon;
		
		private int _Capacidad;
		
		private EntitySet<TD_Reserva_salones_reunione> _TD_Reserva_salones_reuniones;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_SalonChanging(int value);
    partial void OnID_SalonChanged();
    partial void OnNombre_SalonChanging(string value);
    partial void OnNombre_SalonChanged();
    partial void OnCapacidadChanging(int value);
    partial void OnCapacidadChanged();
    #endregion
		
		public TM_Salones_Reunione()
		{
			this._TD_Reserva_salones_reuniones = new EntitySet<TD_Reserva_salones_reunione>(new Action<TD_Reserva_salones_reunione>(this.attach_TD_Reserva_salones_reuniones), new Action<TD_Reserva_salones_reunione>(this.detach_TD_Reserva_salones_reuniones));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Salon", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Salon
		{
			get
			{
				return this._ID_Salon;
			}
			set
			{
				if ((this._ID_Salon != value))
				{
					this.OnID_SalonChanging(value);
					this.SendPropertyChanging();
					this._ID_Salon = value;
					this.SendPropertyChanged("ID_Salon");
					this.OnID_SalonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Salon", DbType="VarChar(30)")]
		public string Nombre_Salon
		{
			get
			{
				return this._Nombre_Salon;
			}
			set
			{
				if ((this._Nombre_Salon != value))
				{
					this.OnNombre_SalonChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Salon = value;
					this.SendPropertyChanged("Nombre_Salon");
					this.OnNombre_SalonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capacidad", DbType="Int NOT NULL")]
		public int Capacidad
		{
			get
			{
				return this._Capacidad;
			}
			set
			{
				if ((this._Capacidad != value))
				{
					this.OnCapacidadChanging(value);
					this.SendPropertyChanging();
					this._Capacidad = value;
					this.SendPropertyChanged("Capacidad");
					this.OnCapacidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Salones_Reunione_TD_Reserva_salones_reunione", Storage="_TD_Reserva_salones_reuniones", ThisKey="ID_Salon", OtherKey="ID_Salon")]
		public EntitySet<TD_Reserva_salones_reunione> TD_Reserva_salones_reuniones
		{
			get
			{
				return this._TD_Reserva_salones_reuniones;
			}
			set
			{
				this._TD_Reserva_salones_reuniones.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TD_Reserva_salones_reuniones(TD_Reserva_salones_reunione entity)
		{
			this.SendPropertyChanging();
			entity.TM_Salones_Reunione = this;
		}
		
		private void detach_TD_Reserva_salones_reuniones(TD_Reserva_salones_reunione entity)
		{
			this.SendPropertyChanging();
			entity.TM_Salones_Reunione = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TD_Reserva_Libro")]
	public partial class TD_Reserva_Libro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Reserva_Libro;
		
		private int _Matricula;
		
		private int _ID_Libro;
		
		private System.DateTime _Inicio_Reserva;
		
		private System.DateTime _Final_Reserva;
		
		private EntityRef<TM_Estudiante> _TM_Estudiante;
		
		private EntityRef<TM_Libro> _TM_Libro;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_Reserva_LibroChanging(int value);
    partial void OnID_Reserva_LibroChanged();
    partial void OnMatriculaChanging(int value);
    partial void OnMatriculaChanged();
    partial void OnID_LibroChanging(int value);
    partial void OnID_LibroChanged();
    partial void OnInicio_ReservaChanging(System.DateTime value);
    partial void OnInicio_ReservaChanged();
    partial void OnFinal_ReservaChanging(System.DateTime value);
    partial void OnFinal_ReservaChanged();
    #endregion
		
		public TD_Reserva_Libro()
		{
			this._TM_Estudiante = default(EntityRef<TM_Estudiante>);
			this._TM_Libro = default(EntityRef<TM_Libro>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Reserva_Libro", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Reserva_Libro
		{
			get
			{
				return this._ID_Reserva_Libro;
			}
			set
			{
				if ((this._ID_Reserva_Libro != value))
				{
					this.OnID_Reserva_LibroChanging(value);
					this.SendPropertyChanging();
					this._ID_Reserva_Libro = value;
					this.SendPropertyChanged("ID_Reserva_Libro");
					this.OnID_Reserva_LibroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matricula", DbType="Int NOT NULL")]
		public int Matricula
		{
			get
			{
				return this._Matricula;
			}
			set
			{
				if ((this._Matricula != value))
				{
					if (this._TM_Estudiante.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMatriculaChanging(value);
					this.SendPropertyChanging();
					this._Matricula = value;
					this.SendPropertyChanged("Matricula");
					this.OnMatriculaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Libro", DbType="Int NOT NULL")]
		public int ID_Libro
		{
			get
			{
				return this._ID_Libro;
			}
			set
			{
				if ((this._ID_Libro != value))
				{
					if (this._TM_Libro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_LibroChanging(value);
					this.SendPropertyChanging();
					this._ID_Libro = value;
					this.SendPropertyChanged("ID_Libro");
					this.OnID_LibroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inicio_Reserva", DbType="DateTime NOT NULL")]
		public System.DateTime Inicio_Reserva
		{
			get
			{
				return this._Inicio_Reserva;
			}
			set
			{
				if ((this._Inicio_Reserva != value))
				{
					this.OnInicio_ReservaChanging(value);
					this.SendPropertyChanging();
					this._Inicio_Reserva = value;
					this.SendPropertyChanged("Inicio_Reserva");
					this.OnInicio_ReservaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Final_Reserva", DbType="DateTime NOT NULL")]
		public System.DateTime Final_Reserva
		{
			get
			{
				return this._Final_Reserva;
			}
			set
			{
				if ((this._Final_Reserva != value))
				{
					this.OnFinal_ReservaChanging(value);
					this.SendPropertyChanging();
					this._Final_Reserva = value;
					this.SendPropertyChanged("Final_Reserva");
					this.OnFinal_ReservaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Estudiante_TD_Reserva_Libro", Storage="_TM_Estudiante", ThisKey="Matricula", OtherKey="Matricula", IsForeignKey=true)]
		public TM_Estudiante TM_Estudiante
		{
			get
			{
				return this._TM_Estudiante.Entity;
			}
			set
			{
				TM_Estudiante previousValue = this._TM_Estudiante.Entity;
				if (((previousValue != value) 
							|| (this._TM_Estudiante.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TM_Estudiante.Entity = null;
						previousValue.TD_Reserva_Libros.Remove(this);
					}
					this._TM_Estudiante.Entity = value;
					if ((value != null))
					{
						value.TD_Reserva_Libros.Add(this);
						this._Matricula = value.Matricula;
					}
					else
					{
						this._Matricula = default(int);
					}
					this.SendPropertyChanged("TM_Estudiante");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Libro_TD_Reserva_Libro", Storage="_TM_Libro", ThisKey="ID_Libro", OtherKey="ID_Libro", IsForeignKey=true)]
		public TM_Libro TM_Libro
		{
			get
			{
				return this._TM_Libro.Entity;
			}
			set
			{
				TM_Libro previousValue = this._TM_Libro.Entity;
				if (((previousValue != value) 
							|| (this._TM_Libro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TM_Libro.Entity = null;
						previousValue.TD_Reserva_Libros.Remove(this);
					}
					this._TM_Libro.Entity = value;
					if ((value != null))
					{
						value.TD_Reserva_Libros.Add(this);
						this._ID_Libro = value.ID_Libro;
					}
					else
					{
						this._ID_Libro = default(int);
					}
					this.SendPropertyChanged("TM_Libro");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TD_Reserva_salones_reuniones")]
	public partial class TD_Reserva_salones_reunione : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Reserva_Salon;
		
		private int _Matricula;
		
		private int _ID_Salon;
		
		private System.DateTime _Inicio_Reserva;
		
		private System.DateTime _Final_Reserva;
		
		private EntityRef<TM_Salones_Reunione> _TM_Salones_Reunione;
		
		private EntityRef<TM_Estudiante> _TM_Estudiante;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_Reserva_SalonChanging(int value);
    partial void OnID_Reserva_SalonChanged();
    partial void OnMatriculaChanging(int value);
    partial void OnMatriculaChanged();
    partial void OnID_SalonChanging(int value);
    partial void OnID_SalonChanged();
    partial void OnInicio_ReservaChanging(System.DateTime value);
    partial void OnInicio_ReservaChanged();
    partial void OnFinal_ReservaChanging(System.DateTime value);
    partial void OnFinal_ReservaChanged();
    #endregion
		
		public TD_Reserva_salones_reunione()
		{
			this._TM_Salones_Reunione = default(EntityRef<TM_Salones_Reunione>);
			this._TM_Estudiante = default(EntityRef<TM_Estudiante>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Reserva_Salon", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Reserva_Salon
		{
			get
			{
				return this._ID_Reserva_Salon;
			}
			set
			{
				if ((this._ID_Reserva_Salon != value))
				{
					this.OnID_Reserva_SalonChanging(value);
					this.SendPropertyChanging();
					this._ID_Reserva_Salon = value;
					this.SendPropertyChanged("ID_Reserva_Salon");
					this.OnID_Reserva_SalonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matricula", DbType="Int NOT NULL")]
		public int Matricula
		{
			get
			{
				return this._Matricula;
			}
			set
			{
				if ((this._Matricula != value))
				{
					if (this._TM_Estudiante.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMatriculaChanging(value);
					this.SendPropertyChanging();
					this._Matricula = value;
					this.SendPropertyChanged("Matricula");
					this.OnMatriculaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Salon", DbType="Int NOT NULL")]
		public int ID_Salon
		{
			get
			{
				return this._ID_Salon;
			}
			set
			{
				if ((this._ID_Salon != value))
				{
					if (this._TM_Salones_Reunione.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_SalonChanging(value);
					this.SendPropertyChanging();
					this._ID_Salon = value;
					this.SendPropertyChanged("ID_Salon");
					this.OnID_SalonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inicio_Reserva", DbType="DateTime NOT NULL")]
		public System.DateTime Inicio_Reserva
		{
			get
			{
				return this._Inicio_Reserva;
			}
			set
			{
				if ((this._Inicio_Reserva != value))
				{
					this.OnInicio_ReservaChanging(value);
					this.SendPropertyChanging();
					this._Inicio_Reserva = value;
					this.SendPropertyChanged("Inicio_Reserva");
					this.OnInicio_ReservaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Final_Reserva", DbType="DateTime NOT NULL")]
		public System.DateTime Final_Reserva
		{
			get
			{
				return this._Final_Reserva;
			}
			set
			{
				if ((this._Final_Reserva != value))
				{
					this.OnFinal_ReservaChanging(value);
					this.SendPropertyChanging();
					this._Final_Reserva = value;
					this.SendPropertyChanged("Final_Reserva");
					this.OnFinal_ReservaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Salones_Reunione_TD_Reserva_salones_reunione", Storage="_TM_Salones_Reunione", ThisKey="ID_Salon", OtherKey="ID_Salon", IsForeignKey=true)]
		public TM_Salones_Reunione TM_Salones_Reunione
		{
			get
			{
				return this._TM_Salones_Reunione.Entity;
			}
			set
			{
				TM_Salones_Reunione previousValue = this._TM_Salones_Reunione.Entity;
				if (((previousValue != value) 
							|| (this._TM_Salones_Reunione.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TM_Salones_Reunione.Entity = null;
						previousValue.TD_Reserva_salones_reuniones.Remove(this);
					}
					this._TM_Salones_Reunione.Entity = value;
					if ((value != null))
					{
						value.TD_Reserva_salones_reuniones.Add(this);
						this._ID_Salon = value.ID_Salon;
					}
					else
					{
						this._ID_Salon = default(int);
					}
					this.SendPropertyChanged("TM_Salones_Reunione");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Estudiante_TD_Reserva_salones_reunione", Storage="_TM_Estudiante", ThisKey="Matricula", OtherKey="Matricula", IsForeignKey=true)]
		public TM_Estudiante TM_Estudiante
		{
			get
			{
				return this._TM_Estudiante.Entity;
			}
			set
			{
				TM_Estudiante previousValue = this._TM_Estudiante.Entity;
				if (((previousValue != value) 
							|| (this._TM_Estudiante.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TM_Estudiante.Entity = null;
						previousValue.TD_Reserva_salones_reuniones.Remove(this);
					}
					this._TM_Estudiante.Entity = value;
					if ((value != null))
					{
						value.TD_Reserva_salones_reuniones.Add(this);
						this._Matricula = value.Matricula;
					}
					else
					{
						this._Matricula = default(int);
					}
					this.SendPropertyChanged("TM_Estudiante");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TM_Espacio_Trabajo")]
	public partial class TM_Espacio_Trabajo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Espacio;
		
		private string _Nombre_Espacio;
		
		private EntitySet<TD_Reserva_Espacio_Trabajo> _TD_Reserva_Espacio_Trabajos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_EspacioChanging(int value);
    partial void OnID_EspacioChanged();
    partial void OnNombre_EspacioChanging(string value);
    partial void OnNombre_EspacioChanged();
    #endregion
		
		public TM_Espacio_Trabajo()
		{
			this._TD_Reserva_Espacio_Trabajos = new EntitySet<TD_Reserva_Espacio_Trabajo>(new Action<TD_Reserva_Espacio_Trabajo>(this.attach_TD_Reserva_Espacio_Trabajos), new Action<TD_Reserva_Espacio_Trabajo>(this.detach_TD_Reserva_Espacio_Trabajos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Espacio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Espacio
		{
			get
			{
				return this._ID_Espacio;
			}
			set
			{
				if ((this._ID_Espacio != value))
				{
					this.OnID_EspacioChanging(value);
					this.SendPropertyChanging();
					this._ID_Espacio = value;
					this.SendPropertyChanged("ID_Espacio");
					this.OnID_EspacioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Espacio", DbType="VarChar(30)")]
		public string Nombre_Espacio
		{
			get
			{
				return this._Nombre_Espacio;
			}
			set
			{
				if ((this._Nombre_Espacio != value))
				{
					this.OnNombre_EspacioChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Espacio = value;
					this.SendPropertyChanged("Nombre_Espacio");
					this.OnNombre_EspacioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Espacio_Trabajo_TD_Reserva_Espacio_Trabajo", Storage="_TD_Reserva_Espacio_Trabajos", ThisKey="ID_Espacio", OtherKey="ID_Espacio")]
		public EntitySet<TD_Reserva_Espacio_Trabajo> TD_Reserva_Espacio_Trabajos
		{
			get
			{
				return this._TD_Reserva_Espacio_Trabajos;
			}
			set
			{
				this._TD_Reserva_Espacio_Trabajos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TD_Reserva_Espacio_Trabajos(TD_Reserva_Espacio_Trabajo entity)
		{
			this.SendPropertyChanging();
			entity.TM_Espacio_Trabajo = this;
		}
		
		private void detach_TD_Reserva_Espacio_Trabajos(TD_Reserva_Espacio_Trabajo entity)
		{
			this.SendPropertyChanging();
			entity.TM_Espacio_Trabajo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TM_Estudiante")]
	public partial class TM_Estudiante : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Matricula;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Email;
		
		private string _Carrera;
		
		private EntitySet<TD_Reserva_Espacio_Trabajo> _TD_Reserva_Espacio_Trabajos;
		
		private EntitySet<TD_Reserva_Libro> _TD_Reserva_Libros;
		
		private EntitySet<TD_Reserva_salones_reunione> _TD_Reserva_salones_reuniones;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMatriculaChanging(int value);
    partial void OnMatriculaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnCarreraChanging(string value);
    partial void OnCarreraChanged();
    #endregion
		
		public TM_Estudiante()
		{
			this._TD_Reserva_Espacio_Trabajos = new EntitySet<TD_Reserva_Espacio_Trabajo>(new Action<TD_Reserva_Espacio_Trabajo>(this.attach_TD_Reserva_Espacio_Trabajos), new Action<TD_Reserva_Espacio_Trabajo>(this.detach_TD_Reserva_Espacio_Trabajos));
			this._TD_Reserva_Libros = new EntitySet<TD_Reserva_Libro>(new Action<TD_Reserva_Libro>(this.attach_TD_Reserva_Libros), new Action<TD_Reserva_Libro>(this.detach_TD_Reserva_Libros));
			this._TD_Reserva_salones_reuniones = new EntitySet<TD_Reserva_salones_reunione>(new Action<TD_Reserva_salones_reunione>(this.attach_TD_Reserva_salones_reuniones), new Action<TD_Reserva_salones_reunione>(this.detach_TD_Reserva_salones_reuniones));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matricula", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Matricula
		{
			get
			{
				return this._Matricula;
			}
			set
			{
				if ((this._Matricula != value))
				{
					this.OnMatriculaChanging(value);
					this.SendPropertyChanging();
					this._Matricula = value;
					this.SendPropertyChanged("Matricula");
					this.OnMatriculaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(30)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(30)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(30)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carrera", DbType="VarChar(30)")]
		public string Carrera
		{
			get
			{
				return this._Carrera;
			}
			set
			{
				if ((this._Carrera != value))
				{
					this.OnCarreraChanging(value);
					this.SendPropertyChanging();
					this._Carrera = value;
					this.SendPropertyChanged("Carrera");
					this.OnCarreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Estudiante_TD_Reserva_Espacio_Trabajo", Storage="_TD_Reserva_Espacio_Trabajos", ThisKey="Matricula", OtherKey="Matricula")]
		public EntitySet<TD_Reserva_Espacio_Trabajo> TD_Reserva_Espacio_Trabajos
		{
			get
			{
				return this._TD_Reserva_Espacio_Trabajos;
			}
			set
			{
				this._TD_Reserva_Espacio_Trabajos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Estudiante_TD_Reserva_Libro", Storage="_TD_Reserva_Libros", ThisKey="Matricula", OtherKey="Matricula")]
		public EntitySet<TD_Reserva_Libro> TD_Reserva_Libros
		{
			get
			{
				return this._TD_Reserva_Libros;
			}
			set
			{
				this._TD_Reserva_Libros.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Estudiante_TD_Reserva_salones_reunione", Storage="_TD_Reserva_salones_reuniones", ThisKey="Matricula", OtherKey="Matricula")]
		public EntitySet<TD_Reserva_salones_reunione> TD_Reserva_salones_reuniones
		{
			get
			{
				return this._TD_Reserva_salones_reuniones;
			}
			set
			{
				this._TD_Reserva_salones_reuniones.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TD_Reserva_Espacio_Trabajos(TD_Reserva_Espacio_Trabajo entity)
		{
			this.SendPropertyChanging();
			entity.TM_Estudiante = this;
		}
		
		private void detach_TD_Reserva_Espacio_Trabajos(TD_Reserva_Espacio_Trabajo entity)
		{
			this.SendPropertyChanging();
			entity.TM_Estudiante = null;
		}
		
		private void attach_TD_Reserva_Libros(TD_Reserva_Libro entity)
		{
			this.SendPropertyChanging();
			entity.TM_Estudiante = this;
		}
		
		private void detach_TD_Reserva_Libros(TD_Reserva_Libro entity)
		{
			this.SendPropertyChanging();
			entity.TM_Estudiante = null;
		}
		
		private void attach_TD_Reserva_salones_reuniones(TD_Reserva_salones_reunione entity)
		{
			this.SendPropertyChanging();
			entity.TM_Estudiante = this;
		}
		
		private void detach_TD_Reserva_salones_reuniones(TD_Reserva_salones_reunione entity)
		{
			this.SendPropertyChanging();
			entity.TM_Estudiante = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TM_Libro")]
	public partial class TM_Libro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Libro;
		
		private string _Nombre_Libro;
		
		private string _Nombre_Autor;
		
		private int _Numero_Paginas;
		
		private string _Genero;
		
		private EntitySet<TD_Reserva_Libro> _TD_Reserva_Libros;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_LibroChanging(int value);
    partial void OnID_LibroChanged();
    partial void OnNombre_LibroChanging(string value);
    partial void OnNombre_LibroChanged();
    partial void OnNombre_AutorChanging(string value);
    partial void OnNombre_AutorChanged();
    partial void OnNumero_PaginasChanging(int value);
    partial void OnNumero_PaginasChanged();
    partial void OnGeneroChanging(string value);
    partial void OnGeneroChanged();
    #endregion
		
		public TM_Libro()
		{
			this._TD_Reserva_Libros = new EntitySet<TD_Reserva_Libro>(new Action<TD_Reserva_Libro>(this.attach_TD_Reserva_Libros), new Action<TD_Reserva_Libro>(this.detach_TD_Reserva_Libros));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Libro", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Libro
		{
			get
			{
				return this._ID_Libro;
			}
			set
			{
				if ((this._ID_Libro != value))
				{
					this.OnID_LibroChanging(value);
					this.SendPropertyChanging();
					this._ID_Libro = value;
					this.SendPropertyChanged("ID_Libro");
					this.OnID_LibroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Libro", DbType="VarChar(50)")]
		public string Nombre_Libro
		{
			get
			{
				return this._Nombre_Libro;
			}
			set
			{
				if ((this._Nombre_Libro != value))
				{
					this.OnNombre_LibroChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Libro = value;
					this.SendPropertyChanged("Nombre_Libro");
					this.OnNombre_LibroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Autor", DbType="VarChar(50)")]
		public string Nombre_Autor
		{
			get
			{
				return this._Nombre_Autor;
			}
			set
			{
				if ((this._Nombre_Autor != value))
				{
					this.OnNombre_AutorChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Autor = value;
					this.SendPropertyChanged("Nombre_Autor");
					this.OnNombre_AutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero_Paginas", DbType="Int NOT NULL")]
		public int Numero_Paginas
		{
			get
			{
				return this._Numero_Paginas;
			}
			set
			{
				if ((this._Numero_Paginas != value))
				{
					this.OnNumero_PaginasChanging(value);
					this.SendPropertyChanging();
					this._Numero_Paginas = value;
					this.SendPropertyChanged("Numero_Paginas");
					this.OnNumero_PaginasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Genero", DbType="VarChar(50)")]
		public string Genero
		{
			get
			{
				return this._Genero;
			}
			set
			{
				if ((this._Genero != value))
				{
					this.OnGeneroChanging(value);
					this.SendPropertyChanging();
					this._Genero = value;
					this.SendPropertyChanged("Genero");
					this.OnGeneroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Libro_TD_Reserva_Libro", Storage="_TD_Reserva_Libros", ThisKey="ID_Libro", OtherKey="ID_Libro")]
		public EntitySet<TD_Reserva_Libro> TD_Reserva_Libros
		{
			get
			{
				return this._TD_Reserva_Libros;
			}
			set
			{
				this._TD_Reserva_Libros.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TD_Reserva_Libros(TD_Reserva_Libro entity)
		{
			this.SendPropertyChanging();
			entity.TM_Libro = this;
		}
		
		private void detach_TD_Reserva_Libros(TD_Reserva_Libro entity)
		{
			this.SendPropertyChanging();
			entity.TM_Libro = null;
		}
	}
}
#pragma warning restore 1591
